version: '2.35.1'


services:
  pg_service:
    image: postgres:alpine
    container_name: pg2
    restart: always
    environment:
      POSTGRES_PASSWORD: 8888
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  bot:
    build: .
    image: exam_bot:latest
    container_name: exam_con
    restart: always
    command: python3 main.py
    depends_on:
      - pg_service


volumes:
  pgdata:



